SPECS/python27.spec: Commenting out python-2.5.1-socketmodule-constants*.patch because these might be causing compile errors like these in socketmodule.c:
Python-2.7.3/Modules/socketmodule.c:4454: error: expected ')' before string constant

Patch13: python-2.5.1-socketmodule-constants.patch
Patch14: python-2.5.1-socketmodule-constants2.patch